device/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [  
    url(r'^device_add/(?P<types>[-\w]+)/$',views.device_add, name='device_create'),
    url(r'^device_update/(?P<types>[-\w]+)/(?P<pk>\d+)/$',views.device_update, name='device_update'),
    url(r'^device_delete/(?P<types>[-\w]+)/(?P<pk>\d+)/$',views.device_delete, name='device_delete'),
    url(r'^$', views.device_list, name='device_list'),
]

project/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^add/$',views.project_add, name='project_add'),
    url(r'^update/(?P<pk>\d+)/$',views.project_update, name='project_update'),
    url(r'^delete/(?P<pk>\d+)/$',views.project_delete, name='project_delete'),
    url(r'^$', views.project_list, name='project_list'),
]

xqms_bmt/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/',include('accounts.urls')),
    url(r'^testcase/', include('testcase.urls',namespace='testcase')),
    url(r'^member/', include('member.urls', namespace='member')),
    url(r'^device/', include('device.urls', namespace='device')),
    url(r'^project/', include('project.urls', namespace='project')),
    url(r'^report/', include('report.urls', namespace='report')),
    url(r'^$', include('project.urls')),
]

project/models.py
from django.db import models
from member.models import Member
from device.models import BaseDevice
# Create your models here.
class Project(models.Model):
    name = models.CharField(max_length=200)

    ## 프로젝트 일정은 datetimekiper 라는 bootstrap ui 사용하면 string 으로
    ## 받아오게 되서 DateTimeField -> CharField 로 바꿈
    start_date = models.CharField(max_length=200)
    end_date = models.CharField(max_length=200)
    comment = models.TextField(null=True,blank=True)

    def __str__(self):
        return self.name

project/forms.py
from django import forms
from .models import Project

class ProjectForm(forms.ModelForm):

    class Meta:
        model = Project
        fields = ['name','start_date','end_date','comment']

# class ProjectDeviceForm(forms.ModelForm):

#     class Meta:
#         model = ProjectDevice
#         fields = ['device']

# class ProjectMemberForm(forms.ModelForm):

#     class Meta:
#         model = ProjectMember
#         fields = ['member']

project/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from project.models import Project
from .forms import ProjectForm
import logging

logger = logging.getLogger(__name__)

@login_required
def project_list(request):
    projects = Project.objects.all()
    param = {
        'title':"프로젝트 리스트", 
        'projects':projects
        }
    return render(request, 'project_list.html', param)

def project_add(request):
    if request.method == "POST":
        logger.error("POST")
        project_form = ProjectForm(request.POST)
        if project_form.is_valid():
            project_form.save()
            return redirect('project:project_list')
        else :
            logger.error("not is_valid()")
            return redirect('project:project_list')
    else :
        project_form = ProjectForm()
        return render(request,'project_form.html',{'project_form':project_form})

## 프로젝트 수정
@login_required
def project_update(request,pk):
    model = get_object_or_404(Project,pk=pk)
    if request.method == "POST":
        project_form = ProjectForm(request.POST,instance=model)
        if project_form.is_valid():
            project_form.save()
            return redirect("project:project_list")
    else :
        project_form = ProjectForm(instance=model)
        return render(request,'project_form.html',{'project_form':project_form})

def project_delete(request,pk):
    project = Project.objects.filter(pk=pk).delete()
    return redirect('project:project_list')

project/templates/project_form.html
{% extends 'base.html' %}
{% block title %}
{{ page_title }}
{% endblock %}

{% block contents %}
<div>
    <form action="." method="POST">
        {% csrf_token %}
        <p>프로젝트 이름 : {{project_form.name}}</p>
        <p>일정 : {{project_form.start_date}} ~ {{project_form.end_date}}</p>
        <p>비고 : {{project_form.comment}}</p>
        <input type="submit" value="확인">
        <a href="{% url 'project:project_list' %}" >취소</a>
    </form>
</div>
{% endblock %}

project/templates/project_list.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}
{{ page_title }}
{% endblock %}

{% block contents %}
<link rel='stylesheet' href='{% static 'fullcalendar/dist/fullcalendar.css' %}'/>
<script src='{% static 'jquery/dist/jquery.js' %}'></script>
<script src='{% static 'moment/moment.js' %}'></script>
<script src='{% static 'fullcalendar/dist/fullcalendar.js' %}'></script>
<script src='{% static 'fullcalendar/dist/locale-all.js' %}'></script>
<script>
    $(document).ready(function() {
        $('#calendar').fullCalendar({
            locale: 'ko',
        // put your options and callbacks here
        events: [
            {% for prj in projects %}
                {
                    title:'{{prj.name }}', 
                    start:'{{prj.start_date}}',
                    end:'{{prj.end_date}}',
                },
            {% endfor %}
            ]
        });
    });
</script>
<h1>{{ page_title }}</h1>
<a href="{% url 'project:project_add' %}">추가</a>
<hr>
<div>
    <!-- <ul>
        {% for project in projects %}
        <li>
            {{project.id}} // {{ project.name }} // <a href="{% url 'project:project_update' project.id %}">수정</a>// <a href="{% url 'project:project_delete' project.id %}">삭제</a> 
        </li>
        {% endfor %}
    </ul> -->
    <table border='1'>
            <thead >
                <tr>
                    <th>No</th>
                    <th>이름</th>    
                    <th>시작일</th>
                    <th>종료일</th>
                    <th>비고</th>
                    <th>수정</th>
                    <th>삭제</th>
                </tr>
            </thead>
            <tbody>
                {% for project in projects %}
                <tr>
                    <td>{{project.id}}</td>
                    <td>{{project.name}}</td>
                    <td>{{project.start_date}}</td>
                    <td>{{project.end_date}}</td>
                    <td>{{project.comment}}</td>
                    <td><a href="{% url 'project:project_update' project.id %}">수정</a></td>
                    <td><a href="{% url 'project:project_delete' project.id %}">삭제</a></td>
                </tr>
                {% endfor %}
            </tbody>
    
        </table>   
</div>
<div id='calendar'></div>
{% endblock %}