device/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [  
    url(r'^device_add/(?P<types>[-\w]+)/$',views.device_add, name='device_create'),
    url(r'^device_update/(?P<types>[-\w]+)/(?P<pk>\d+)/$',views.device_update, name='device_update'),
    url(r'^device_delete/(?P<types>[-\w]+)/(?P<pk>\d+)/$',views.device_delete, name='device_delete'),
    url(r'^$', views.device_list, name='device_list'),
]

xqms_bmt/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/',include('accounts.urls')),
    url(r'^testcase/', include('testcase.urls',namespace='testcase')),
    url(r'^member/', include('member.urls', namespace='member')),
    url(r'^device/', include('device.urls', namespace='device')),
    url(r'^project/', include('project.urls', namespace='project')),
    url(r'^report/', include('report.urls', namespace='report')),
    url(r'^$', include('project.urls')),
]

device/models.py
from django.db import models

class BaseDevice(models.Model):
    
    name = models.CharField(max_length=50)
    model = models.CharField(max_length=20)
    manufacturer = models.CharField(max_length=20)
    
    service = models.CharField(max_length=10)
    firmware = models.CharField(max_length=50)
    image = models.ImageField(null=True)
    #등록일 수정일
    created = models.DateTimeField(auto_now_add = True)
    updated = models.DateTimeField(auto_now=True, null=True)
    comment = models.CharField(max_length=200, null=True)

    def __str__(self):
        return self.name

class Settopbox(BaseDevice):
    mac_address = models.CharField(max_length=50, unique=True)

class AccessPoint(BaseDevice):
    mac_address = models.CharField(max_length=50, unique=True)

class RemoteController(BaseDevice):
    pass

device/forms.py
from django import forms
from .models import Settopbox,AccessPoint,RemoteController,BaseDevice


class SettopboxCreateForm(forms.ModelForm):
    
    class Meta:
        model = Settopbox
        fields=['name', 'model','manufacturer','service','firmware','comment','mac_address']
    

class AccessPointCreateForm(forms.ModelForm):
    
    class Meta:
        model = AccessPoint
        fields=['name', 'model','manufacturer','service','firmware','comment','mac_address']


class RemoteControllerCreateForm(forms.ModelForm):
    
    class Meta:
        model = RemoteController
        fields=['name', 'model','manufacturer','service','firmware','comment']

device/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import CreateView, DeleteView, UpdateView, TemplateView
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse_lazy 

from .models import BaseDevice, Settopbox, AccessPoint, RemoteController
from .forms import AccessPointCreateForm,SettopboxCreateForm,RemoteControllerCreateForm
import logging

logger = logging.getLogger(__name__)

@login_required
def device_list(request):
    devices_stb = Settopbox.objects.all()
    devices_ap = AccessPoint.objects.all()
    devices_rc = RemoteController.objects.all()
    param = {
        'title':"장치 리스트", 
        'devices_stb':devices_stb,
        'devices_ap':devices_ap,
        'devices_rc':devices_rc
        }
    return render(request, 'device_list.html', param)

##장비 추가(STB,AP,리모컨)
def device_add(request,types):
    try :
        if request.method == "POST":
            if types == "STB":
                forms = SettopboxCreateForm(request.POST)
                if forms.is_valid():
                    forms.save()
                    return redirect('device:device_list')
            elif types == "AP":
                forms = AccessPointCreateForm(request.POST)
                if forms.is_valid():
                    forms.save()
                    return redirect('device:device_list')
            elif types == "RC":
                forms = RemoteControllerCreateForm(request.POST)
                if forms.is_valid():
                    forms.save()
                    return redirect('device:device_list')          
        else :
            if types == "STB" :
                forms = SettopboxCreateForm()
                name = "STB 등록"
                types = "STB"
                return render(request, 'basedevice_form.html',{'form':forms,'name':name,'types':types})
            elif types == "AP" :
                forms = AccessPointCreateForm()
                name = "AP 등록"
                types = "AP"
                return render(request, 'basedevice_form.html',{'form':forms,'name':name,'types':types})
            elif types == "RC" :
                forms = RemoteControllerCreateForm()
                name = "리모컨 등록"
                types = "RC"
                return render(request, 'basedevice_form.html',{'form':forms,'name':name,'types':types}) 
    except Exception as e :
        logger.error(e)

## 장비 수정(STB,AP,리모컨)
def device_update(request,types,pk):
    try:
        if request.method == "POST":
             if types == "STB":
                model = get_object_or_404(Settopbox,pk=pk)
                forms = SettopboxCreateForm(request.POST,instance=model)
                if forms.is_valid():
                    forms.save()
                    return redirect('device:device_list')
             elif types == "AP":
                model = get_object_or_404(AccessPoint,pk=pk)
                forms = AccessPointCreateForm(request.POST,instance=model)
                if forms.is_valid():
                    forms.save()
                    return redirect('device:device_list') 
             elif types == "RC":
                model = get_object_or_404(RemoteController,pk=pk)
                forms = RemoteControllerCreateForm(request.POST,instance=model)
                if forms.is_valid():
                    forms.save()
                    return redirect('device:device_list')                                               
        else :
            if types == "STB" :
                model = get_object_or_404(Settopbox,pk=pk)
                forms = SettopboxCreateForm(instance=model)
                name = "STB 수정"
                types = "STB"
                return render(request, 'basedevice_form.html',{'form':forms,'name':name,'types':types})
            elif types == "AP" :
                model = get_object_or_404(AccessPoint,pk=pk)
                forms = AccessPointCreateForm(instance=model)
                name = "AP 수정"
                types = "AP"
                return render(request, 'basedevice_form.html',{'form':forms,'name':name,'types':types})
            elif types == "RC" :
                model = get_object_or_404(RemoteController,pk=pk)
                forms = RemoteControllerCreateForm(instance=model)
                name = "리모컨 수정"
                types = "RC"
                return render(request, 'basedevice_form.html',{'form':forms,'name':name,'types':types})            
    except Exception as e:
        logger.error(e)

def device_delete(request,types,pk):
    if types == "STB":
        device = Settopbox.objects.filter(pk=pk).delete()
        return redirect('device:device_list')
    elif types == "AP":
        device = AccessPoint.objects.filter(pk=pk).delete()
        return redirect('device:device_list')
    elif types == "RC":
        device = RemoteController.objects.filter(pk=pk).delete()
        return redirect('device:device_list')

device/templates/basedevice_form.html
{% extends 'base.html' %}
{% block title %}
{{ page_title }}
{% endblock %}

{% block contents %}
    {{name}}
    <form action="." method="POST">
        {{form.as_p}}
        {% csrf_token %}
        <input type="submit" value="확인">
        <a href="{% url 'device:device_list' %}" >취소</a>
    </form>
{% endblock %}

device/templates/device_list.html
{% extends 'base.html' %}
{% block title %}
{{ page_title }}
{% endblock %}

{% block contents %}
<a href="{% url 'device:device_create' 'STB' %}">STB 추가</a>
<a href="{% url 'device:device_create' 'AP' %}">AP 추가</a>
<a href="{% url 'device:device_create' 'RC' %}">리모컨 추가</a>
<hr>
<div>
    <p>STB 목록</p>
    <table border='1'>
            <thead >
                <tr>
                    <th>No</th>
                    <th>이름</th>
                    <th>모델명</th>
                    <th>제조사</th>
                    <th>Service</th>
                    <th>펌웨어</th>
                    <th>비고</th>
                    <th>MAC 주소</th>
                    <th>수정</th>
                    <th>삭제</th>
                </tr>
            </thead>
            <tbody>
                {% for device in devices_stb %}
                <tr>
                    <td>{{device.id}}</td>
                    <td>{{device.name}}</td>
                    <td>{{device.model}}</td>
                    <td>{{device.manufacturer}}</td>
                    <td>{{device.service}}</td>
                    <td>{{device.firmware}}</td>
                    <td>{{device.comment}}</td>
                    <th>{{device.mac_address}}</th>
                    <td><a href="{% url 'device:device_update' 'STB' device.id %}">수정</a></td>
                    <td><a href="{% url 'device:device_delete' 'STB' device.id %}">삭제</a></td>
                </tr>
                {% endfor %}
            </tbody>
    
        </table>
        <p>AP 목록</p>
        <table border='1'>
                <thead >
                    <tr>
                        <th>No</th>
                        <th>이름</th>
                        <th>모델명</th>
                        <th>제조사</th>
                        <th>Service</th>
                        <th>펌웨어</th>
                        <th>비고</th>
                        <th>MAC 주소</th>
                        <th>수정</th>
                        <th>삭제</th>
                    </tr>
                </thead>
                <tbody>
                    {% for device in devices_ap %}
                    <tr>
                        <td>{{device.id}}</td>
                        <td>{{device.name}}</td>
                        <td>{{device.model}}</td>
                        <td>{{device.manufacturer}}</td>
                        <td>{{device.service}}</td>
                        <td>{{device.firmware}}</td>
                        <td>{{device.comment}}</td>
                        <th>{{device.mac_address}}</th>
                        <td><a href="{% url 'device:device_update' 'AP' device.id %}">수정</a></td>
                        <td><a href="{% url 'device:device_delete' 'AP' device.id %}">삭제</a></td>
                    </tr>
                    {% endfor %}
                </tbody>
        
            </table> 
            <p>리모컨 목록</p>
            <table border='1'>
                    <thead >
                        <tr>
                            <th>No</th>
                            <th>이름</th>
                            <th>모델명</th>
                            <th>제조사</th>
                            <th>Service</th>
                            <th>펌웨어</th>
                            <th>비고</th>
                            <th>수정</th>
                            <th>삭제</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for device in devices_rc %}
                        <tr>
                            <td>{{device.id}}</td>
                            <td>{{device.name}}</td>
                            <td>{{device.model}}</td>
                            <td>{{device.manufacturer}}</td>
                            <td>{{device.service}}</td>
                            <td>{{device.firmware}}</td>
                            <td>{{device.comment}}</td>
                            <td><a href="{% url 'device:device_update' 'RC' device.id %}">수정</a></td>
                            <td><a href="{% url 'device:device_delete' 'RC' device.id %}">삭제</a></td>
                        </tr>
                        {% endfor %}
                    </tbody>
            
                </table>      
</div>
{% endblock %}