device/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [  
    url(r'^device_add/(?P<types>[-\w]+)/$',views.device_add, name='device_create'),
    url(r'^device_update/(?P<types>[-\w]+)/(?P<pk>\d+)/$',views.device_update, name='device_update'),
    url(r'^device_delete/(?P<types>[-\w]+)/(?P<pk>\d+)/$',views.device_delete, name='device_delete'),
    url(r'^$', views.device_list, name='device_list'),
]

member/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^add/$',views.member_add, name='member_add'),
    url(r'^update/(?P<pk>\d+)/$',views.member_update, name ='member_update'),
    url(r'^delete/(?P<pk>\d+)/$',views.member_delete, name = 'member_delete'),
    url(r'^$', views.member_list, name='member_list'),
]

project/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^add/$',views.project_add, name='project_add'),
    url(r'^update/(?P<pk>\d+)/$',views.project_update, name='project_update'),
    url(r'^delete/(?P<pk>\d+)/$',views.project_delete, name='project_delete'),
    url(r'^$', views.project_list, name='project_list'),
]

report/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.report_list, name='report_list'),
]

testcase/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^add/$',views.testcase_add, name='testcase_add'),
    url(r'update/(?P<pk>\d+)/$',views.testcase_update, name='testcase_update'),
    url(r'delete/(?P<pk>\d+)/$',views.testcase_delete, name='testcase_delete'),
    url(r'^$',views.testCase_list, name='testcase_list'),
]

xqms_bmt/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/',include('accounts.urls')),
    url(r'^testcase/', include('testcase.urls',namespace='testcase')),
    url(r'^member/', include('member.urls', namespace='member')),
    url(r'^device/', include('device.urls', namespace='device')),
    url(r'^project/', include('project.urls', namespace='project')),
    url(r'^report/', include('report.urls', namespace='report')),
    url(r'^$', include('project.urls')),
]

templates/base.html
<!DOCTYPE html>
<html lang="ko">
    <head>
        <meta charset="UTF-8">
        <title>{{ title }}</title>
    </head>
    <body>
        <nav>
            <ul>
                {% if user.is_active %}
                    <li>Welcom, {{user.get_username}}</li>
                    <li><a href="{% url 'logout' %}">Logout</a></li>
                {% else %}
                    <li><a href="{% url 'login' %}">Login</a></li>
                    <li><a href="{% url 'register' %}">회원가입</a></li>
                {% endif %}
            </ul>
        </nav>
        <h1>{{ title }}</h1>
        <a href="{% url 'project:project_list' %}">프로젝트</a> /
        <a href="{% url 'report:report_list' %}">리포트</a> / 
        <a href="{% url 'device:device_list' %}">장치</a> / 
        <a href="{% url 'member:member_list' %}">회원</a> /
        <a href="{% url 'testcase:testcase_list' %}">테스트현황</a>
        <hr>

        {% block contents %}
        {% endblock %}
    </body>
    <footer>
        <hr>
        {{ footer }}
    </footer>
</html>