device/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [  
    url(r'^device_add/(?P<types>[-\w]+)/$',views.device_add, name='device_create'),
    url(r'^device_update/(?P<types>[-\w]+)/(?P<pk>\d+)/$',views.device_update, name='device_update'),
    url(r'^device_delete/(?P<types>[-\w]+)/(?P<pk>\d+)/$',views.device_delete, name='device_delete'),
    url(r'^$', views.device_list, name='device_list'),
]

member/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^add/$',views.member_add, name='member_add'),
    url(r'^update/(?P<pk>\d+)/$',views.member_update, name ='member_update'),
    url(r'^delete/(?P<pk>\d+)/$',views.member_delete, name = 'member_delete'),
    url(r'^$', views.member_list, name='member_list'),
]

xqms_bmt/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/',include('accounts.urls')),
    url(r'^testcase/', include('testcase.urls',namespace='testcase')),
    url(r'^member/', include('member.urls', namespace='member')),
    url(r'^device/', include('device.urls', namespace='device')),
    url(r'^project/', include('project.urls', namespace='project')),
    url(r'^report/', include('report.urls', namespace='report')),
    url(r'^$', include('project.urls')),
]

member/models.py
from django.db import models

class Department(models.Model):
    #부서명
    name = models.CharField(max_length=50)
    #코멘트
    comment = models.CharField(max_length=200)

    def __str__(self):
        return self.name

class Member(models.Model):
    #이름
    name = models.CharField(max_length=50)
    #연락처
    phone_number = models.CharField(max_length=50)
    email_address = models.EmailField()
    #부서
    department = models.ForeignKey('Department')
    #코멘트
    comment = models.CharField(max_length=200)
    #등록일 수정일
    created = models.DateTimeField(auto_now_add = True)
    updated = models.DateTimeField(auto_now=True)
    #활성
    enable = models.BooleanField(default=True)

    def __str__(self):
        return self.name

member/forms.py
from django import forms
from .models import Member

class MemberCreateForm(forms.ModelForm):
    #password = forms.CharField(label="Password", widget=forms.PasswordInput)
    #password2 = forms.CharField(label="RepeatPassword",widget=forms.PasswordInput)

    class Meta:
        model = Member
        fields =['name','department','email_address','phone_number']

    # def clean_password2(self):
    #     cd = self.cleaned_data
    #     if cd['password'] != cd['password2']:
    #         raise forms.ValidationError('비밀번호가 올바르지 않습니다.')
    #     return cd['password']

        

member/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from .models import Member, Department
from .forms import MemberCreateForm

import logging

logger = logging.getLogger(__name__)

@login_required
def member_list(request):
    members = Member.objects.all()
    param = {
        'title':"멤버리스트", 
        'members':members
        }
    return render(request, 'member_list.html', param)

def member_add(request):
    if request.method == "POST":
        form = MemberCreateForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('member:member_list')
    else :
        form = MemberCreateForm()
        return render(request, 'member_form.html',{'form':form})

## 회원 수정
def member_update(request,pk):
    model = get_object_or_404(Member,pk=pk)
    if request.method == "POST":
        form = MemberCreateForm(request.POST,instance=model)
        if form.is_valid():
            form.save()
            return redirect('member:member_list')
    else :
        form = MemberCreateForm(instance=model)
        return render(request,'member_form.html',{'form':form})

def member_delete(request,pk):
    member = Member.objects.filter(pk=pk).delete()
    return redirect('member:member_list')

member/templates/member_form.html
{% extends 'base.html' %}
{% block title %}
{{ page_title }}
{% endblock %}

{% block contents %}
<div>
    <form action="." method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="확인">
        <a href="{% url 'member:member_list' %}" >취소</a>
    </form>
</div>
{% endblock %}

member/templates/member_list.html
{% extends 'base.html' %}
{% block title %}
{{ page_title }}
{% endblock %}

{% block contents %}
<h1>{{ page_title }}</h1>
<p><a href="{% url 'member:member_add' %}">등록</a></p>
<div>
    <!-- <ul>
        {% for member in members %}
        <li>
            {{ member.name }}  //  <a href="{% url 'member:member_update' member.id %}">수정</a> // <a href="{% url 'member:member_delete' member.id %}">삭제</a>
        </li>
        {% endfor %}
    </ul> -->
    <table border='1'>
            <thead >
                <tr>
                    <th>No</th>
                    <th>부서</th>    
                    <th>이름</th>
                    <th>이메일주소</th>
                    <th>핸드폰 번호</th>
                    <th>활성화상태</th>
                    <th>수정</th>
                    <th>삭제</th>
                </tr>
            </thead>
            <tbody>
                {% for member in members %}
                <tr>
                    <td>{{member.id}}</td>
                    <td>{{member.name}}</td>
                    <td>{{member.department}}</td>
                    <td>{{member.email_address}}</td>
                    <td>{{member.phone_number}}</td>
                    <td>{{member.enable}}</td>
                    <td><a href="{% url 'member:member_update' member.id %}">수정</a></td>
                    <td><a href="{% url 'member:member_delete' member.id %}">삭제</a></td>
                </tr>
                {% endfor %}
            </tbody>
    
        </table>    
</div>
{% endblock %}